name: remote_data_provider
description: Help implementing providers easier with predefined abstract classes, special is for working with remote data.
version: 0.0.1
homepage: https://github.com/ngoan98tv/remote_data_provider

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.4.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
