name: remote_data_provider
description: Help implementing providers easier with predefined abstract classes, special is for working with remote data.
version: 2.4.3
homepage: https://github.com/ngoan98tv/remote_data_provider

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
