name: remote_data_provider
description: A new Flutter package project.
version: 0.0.1
author: ngoan98travinh@gmail.com
homepage: 

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
