name: Publish

on:
  push:
    branches: [ pub ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: mkdir ~/.pub-cache
    - run: echo secrets.PUB_CREDENTIALS > ~/.pub-cache/credentials.json
    - run: flutter pub get
    - run: flutter test
    - run: flutter pub publish --force
