name: Publish

on:
  push:
    branches: [ pub ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
      with:
        credential: ${{ secrets.PUB_CREDENTIALS }}
